/**
 * Extra questions for the foot of each article.
 *
 * Every H2 in these articles is already a question, and the FAQPage schema is built from
 * those. So this file exists to add, not to repeat: nothing here duplicates a heading in
 * the body. These are the practical ones a patient types after they have read the piece —
 * where to go, what to bring, whether it applies to someone else in the house — plus the
 * misconceptions common enough in Chennai to be worth answering by name.
 *
 * Same three limits as the rest of the site: nothing claims a capability beyond what AJSMC
 * publishes, nothing promises a cure, and no fees or doses appear. Where an answer needs a
 * number the article already carries, it points at the section rather than restating it, so
 * the two cannot drift apart.
 */
export const articleFaqs: Record<string, { q: string; a: string }[]> = {
  "monsoon-fever": [
    { q: "Can I get dengue and chikungunya at the same time?",
      a: "Yes. Both are spread by the same Aedes mosquito, and in a Chennai monsoon the same person can be bitten by more than one infected mosquito. A doctor treats what is in front of them rather than assuming one diagnosis rules out another, which is another reason the day of fever matters more than a single test result." },
    { q: "Does a normal blood count on day 2 mean I am in the clear?",
      a: "No. Early in any of these four illnesses the counts can still look ordinary. That is why the guidance is to repeat rather than to reassure, and why a fever that carries on past three days is followed up whatever the first report showed." },
    { q: "Should the rest of the family be tested if one person has dengue?",
      a: "Not routinely. Testing follows symptoms, not household contact. What the household should do instead is clear standing water around the home, because the mosquito that bit one person is breeding within a short distance of it." },
    { q: "Can I go to work with a monsoon fever?",
      a: "Rest matters more than most people expect in these illnesses, and the first few days are when warning signs appear. Someone who needs to be watched for warning signs should be somewhere they can be watched." },
    { q: "Which department at AJSMC do I book for a monsoon fever?",
      a: "General Medicine. Outpatient consultations run Monday to Saturday, 10am to 9pm at Police Commissioner Office Road, Egmore, and blood tests ordered on the day are processed in the building. Call 044 2532 2021 to check when a consultant is in." },
  ],
  "dengue-platelets": [
    { q: "How often will the platelet count be repeated?",
      a: "As often as the illness needs, which your consultant decides from the day of fever and how you are rather than from a fixed schedule. A single number in isolation says very little; the direction it is moving in says more." },
    { q: "Can I stop the blood tests once I start feeling better?",
      a: "Feeling better is not the same as being past the risk window in dengue, and the point at which people feel a little better is close to the point at which warning signs appear. Follow the review your doctor set rather than your own sense of improvement." },
    { q: "Is a low platelet count in dengue the same as low platelets from any other cause?",
      a: "No. The fall in dengue is part of the illness and usually recovers on its own. A low count found on a routine report with no fever is a different question and is worked up differently." },
    { q: "Can children get dengue with a normal platelet count?",
      a: "Yes. A normal count does not exclude dengue at any age, which is why the warning signs are watched rather than the number alone." },
    { q: "Where should I go if warning signs appear at night?",
      a: "Straight to a hospital with a 24-hour emergency department, or call 108. AJSMC is an outpatient and day-care centre in Egmore with no casualty unit and no doctor on the premises overnight, and its beds take planned, stable admissions rather than anyone whose condition may worsen. Consultations run Monday to Saturday, 10am to 9pm." },
  ],
  leptospirosis: [
    { q: "Can leptospirosis be caught from drinking water?",
      a: "The route this article is about is contact with water contaminated by animal urine, especially through a cut or graze. Municipal drinking water is a separate question. If you waded through floodwater, that exposure is the one to mention at the consultation." },
    { q: "How long after wading through floodwater should I stay alert for fever?",
      a: "The window is wide, which is the point of the article: fever can begin days to weeks after the exposure. Note the date you were in the water and take it with you, because it changes what a doctor tests for." },
    { q: "Do I need to tell the doctor about floodwater if I have no wound?",
      a: "Yes, mention it either way. Intact skin soaked for long enough is still an exposure, and the doctor is deciding what to test rather than judging how careful you were." },
    { q: "Are children and outdoor workers at higher risk in Chennai?",
      a: "Anyone with repeated contact with floodwater, wet mud, sewage or animals has more exposure, and children playing in standing water are in that group. The exposure is what raises the risk, not the person." },
    { q: "Which department do I book at AJSMC for this?",
      a: "General Medicine, Monday to Saturday, 10am to 9pm in Egmore. Blood tests ordered during the consultation are run in the laboratory here, so most reports reach your consultant in the same visit. Call 044 2532 2021 first if you want to know when a consultant is in." },
  ],
  "child-fever": [
    { q: "Can I give my child a bath while they have a fever?",
      a: "A normal bath in comfortably warm water is fine and often makes a child feel better. What the article warns against is cold water and sponging to force the temperature down, which is a different thing." },
    { q: "Should I wake my child to give fever medicine?",
      a: "Sleep is doing more good than a lower number on a thermometer. Medicine is for discomfort, not for the reading, so a child who is sleeping comfortably is usually best left to sleep." },
    { q: "How long should a child stay home from school after a fever?",
      a: "Until they are eating, drinking and behaving like themselves, and the fever has settled without medicine. Schools in Chennai often ask for a day clear of fever, and that is a reasonable rule for the child as well as the class." },
    { q: "My child's hands and feet are cold but the forehead is hot. Is that serious?",
      a: "It is common while a temperature is rising and is not by itself a warning sign. What matters is the list in this article: how the child is drinking, breathing, passing urine and responding to you." },
    { q: "Can I bring my child to AJSMC without an appointment?",
      a: "Walk-in patients are seen Monday to Saturday, 10am to 9pm, though calling 044 2532 2021 first means less waiting and confirms the paediatric consultant is in. For anything on the urgent list in this article, go to a hospital with a 24-hour emergency department instead." },
  ],
  "child-vaccination": [
    { q: "Can vaccines be given if my child has a mild cold?",
      a: "A mild illness without fever is usually not a reason to postpone. The article sets out what does postpone a dose, and that judgement is made at the visit rather than at home." },
    { q: "Does the vaccination card matter if we move cities?",
      a: "It matters a great deal. The card is the only record of what was given and when, and without it a new clinic has to work from memory. Photograph it and keep the paper copy." },
    { q: "Can two vaccines be given on the same day?",
      a: "Giving more than one at a visit is routine and is how the schedule is designed to work. Splitting them across extra visits mostly adds trips and delay." },
    { q: "What if my child is unwell on the day the dose is due?",
      a: "Call 044 2532 2021 and describe it rather than deciding either way at home. A dose delayed by a few days is not a schedule restarted, which the article explains in the missed-dose section." },
    { q: "Which department handles vaccination at AJSMC?",
      a: "Paediatrics, Monday to Saturday, 10am to 9pm at Police Commissioner Office Road, Egmore. Bring the vaccination card or any record you have so the consultant can see what has been given and what is due." },
  ],
  "vomiting-loose-motion": [
    { q: "Can I use a sports drink instead of ORS?",
      a: "No. This article explains which home fluids help and which make things worse, and drinks made for exercise are in the second group. Standardised ORS exists because the proportions matter." },
    { q: "How do I store ORS once it is mixed?",
      a: "Make it fresh, keep it covered, and throw away what is left at the end of the day. Mixing a fresh packet is safer than keeping yesterday's." },
    { q: "Is it safe to travel with loose motion?",
      a: "The risk is dehydration rather than the journey. Someone who cannot keep fluids down, or who has any of the dehydration signs in this article, should be seen before travelling rather than after." },
    { q: "Can the whole family catch this?",
      a: "Many of these infections spread within a household through hands and shared food. Handwashing and separate towels do more than anything bought at a pharmacy." },
    { q: "Which department at AJSMC should I book?",
      a: "General Medicine for adults, Paediatrics for a child, Monday to Saturday, 10am to 9pm. Stool and blood tests ordered on the day are processed in the laboratory here." },
  ],
  "high-sugar-screening": [
    { q: "Can I eat normally before coming for the confirmatory test?",
      a: "It depends which test is being done, which the article sets out. Call 044 2532 2021 before you come and ask, so you do not fast unnecessarily or give a sample that cannot be interpreted." },
    { q: "Does the camp reading go on my medical record?",
      a: "The programme records it as a referral, not a diagnosis, and the slip says suspected. What goes on your record at a hospital is the laboratory result." },
    { q: "Should my family be tested if my camp reading was high?",
      a: "Diabetes runs in families, and Indian guidance starts screening earlier than most people expect. If close relatives have not been tested recently, this is a reasonable prompt." },
    { q: "What if I lost the referral slip from the camp?",
      a: "Come anyway. The slip is useful but the consultation does not depend on it; what matters is the reading, roughly when it was taken and what you have felt since." },
    { q: "Which department do I book at AJSMC?",
      a: "Diabetology, Monday to Saturday, 10am to 9pm in Egmore. The laboratory is in the building, so tests ordered during the consultation are processed here and most reports reach your consultant in the same visit." },
  ],
  "first-diabetes-visit": [
    { q: "Can I bring my home glucometer readings instead of a lab report?",
      a: "Bring both. Home readings show the pattern across a week in a way a single laboratory value cannot, and the article lists what the visit uses each of them for." },
    { q: "Will I be started on medicines at the first visit?",
      a: "That is a decision your consultant makes from your results and your history, not something to expect either way. What the visit is certain to cover is the checks the article lists." },
    { q: "Do I need to fast for the eye and foot checks?",
      a: "No. Fasting applies only to certain blood tests, and the eye and foot examinations are unaffected by whether you have eaten." },
    { q: "How long does a first diabetes consultation take?",
      a: "Longer than a follow-up, because the history, the examination and the baseline tests all happen at once. Come with time in hand rather than between two other things." },
    { q: "Can I see the same consultant at every visit?",
      a: "Continuity helps in a long-term condition. Consultants keep their own clinic hours inside Monday to Saturday, 10am to 9pm, so call 044 2532 2021 and ask when yours is in." },
  ],
  "fatty-liver-grades": [
    { q: "Can I ask for the FIB-4 to be calculated from my old reports?",
      a: "Yes, and this article explains why: it is worked out from values that are often already in your file, so it frequently needs no new blood test at all. Bring the old reports." },
    { q: "Does a fatty liver report mean I should stop all fat in my diet?",
      a: "That is not what the grade is about. This article covers what actually changes the picture, and a blanket ban on dietary fat is not on that list. Take the report to a consultant before rewriting your diet." },
    { q: "Should the scan be repeated at a different centre for a second opinion?",
      a: "The article explains how much the grade itself varies between operators, which is the honest answer to this. A second scan often adds another opinion rather than more certainty; staging the fibrosis is what adds information." },
    { q: "Is fatty liver a reason to stop prescribed medicines?",
      a: "Never stop a prescribed medicine on the strength of a scan report. Take the report and the medicine strips to the consultant who prescribed them." },
    { q: "Which department at AJSMC should I book with a fatty liver report?",
      a: "General Medicine, Monday to Saturday, 10am to 9pm in Egmore. Bring the scan report itself along with any earlier blood reports, and the strips of anything you take." },
  ],
  "health-checkup-after-40": [
    { q: "How early should I arrive for fasting blood tests?",
      a: "Come early in the outpatient hours, which start at 10am, so the fast is not longer than it needs to be. Call 044 2532 2021 the day before to confirm which of your tests need one." },
    { q: "Can I take my regular medicines on the morning of the tests?",
      a: "Ask when you book rather than deciding at home, because it depends on the medicine and on which tests are being done. Bring the strips with you either way." },
    { q: "How often should this be repeated if everything is normal?",
      a: "The interval depends on your results and your family history, and it is set by the consultant who saw them. A normal set of results is a baseline to measure against, not a reason to stop." },
    { q: "Can I do this checkup while I am unwell?",
      a: "A screening check is for when you are well. An acute illness shifts several of these values, and a report taken during one can mislead in both directions." },
    { q: "Do I need a referral to book a health checkup at AJSMC?",
      a: "No. Book directly on 044 2532 2021, by WhatsApp, or through the form on this site. Consultations run Monday to Saturday, 10am to 9pm and the laboratory is in the building." },
  ],
  "pap-smear": [
    { q: "Can I have a Pap smear during my period?",
      a: "It is usually deferred, because blood makes the sample harder to read. This article lists what else to avoid in the days beforehand; call 044 2532 2021 to move the appointment rather than skipping it." },
    { q: "Does the test hurt?",
      a: "Most women describe pressure rather than pain, and it is over in a few minutes. The article describes what actually happens in the room, which is usually the part people are anxious about." },
    { q: "Can I come for this without my husband knowing?",
      a: "Yes. Consultations are private and records stay confidential. You can book directly for yourself." },
    { q: "How long do the results take?",
      a: "Cytology takes longer than an ordinary blood test because a person examines the slide. Your consultant will tell you when to expect it and how it will reach you." },
    { q: "Which department do I book at AJSMC for a Pap smear?",
      a: "Obstetrics and Gynaecology, Monday to Saturday, 10am to 9pm at Police Commissioner Office Road, Egmore. Bring any previous screening reports if you have them." },
  ],
  "pcos-testing": [
    { q: "What if my cycles are so irregular that I cannot count the right day?",
      a: "Say exactly that at the consultation. It is a common situation in PCOS and it is one the consultant plans around; it is not a reason to guess a date and have the tests wasted." },
    { q: "Can I be tested while on hormonal contraception?",
      a: "It changes what several of these results mean, so tell the consultant what you are taking and for how long. Do not stop a prescribed medicine to get a test done." },
    { q: "Does a normal scan rule PCOS out?",
      a: "No. This article explains what the scan does and does not settle, and why the diagnosis is not made from imaging alone." },
    { q: "Will I need the same tests repeated every year?",
      a: "Some are repeated to follow the things PCOS affects over time, which the article covers, and some are done once. Your consultant sets the interval from your own results." },
    { q: "Which department at AJSMC handles PCOS testing?",
      a: "Obstetrics and Gynaecology, Monday to Saturday, 10am to 9pm in Egmore. Blood tests ordered on the day are processed in the laboratory here. Bring the dates of your last few periods." },
  ],
  "counselling-first-session": [
    { q: "How many sessions will I need?",
      a: "That is discussed with you rather than decided in advance, and it depends on what you come with. The first session is where the pace is set." },
    { q: "Can I change counsellor if it does not feel right?",
      a: "Yes. Fit matters in counselling and saying it is not working is a reasonable thing to say. Call 044 2532 2021 and ask." },
    { q: "Do I have to talk about my childhood?",
      a: "No. You set what is discussed and you are not obliged to go into anything you are not ready for. The first session is mostly listening." },
    { q: "Can I bring someone with me to the first session?",
      a: "You can bring someone to the centre, and whether they come into the room is your decision. For anyone under 18, this article explains how consent works." },
    { q: "How do I book a counselling appointment at AJSMC?",
      a: "Call 044 2532 2021, message the same number on WhatsApp, or use the appointment form on this site. Sessions run inside outpatient hours, Monday to Saturday, 10am to 9pm in Egmore. No referral is needed." },
  ],
  "how-fast-you-age": [
    { q: "Is it too late to start in my fifties or sixties?",
      a: "The evidence in this article on exercise and muscle does not have an upper age cut-off, and the gains from starting are largest in people who were doing least. Later is not the same as too late." },
    { q: "Do I need a gym to get the exercise the evidence supports?",
      a: "No. What the studies measure is the amount and the intensity, not the venue. The article gives the numbers; how you reach them is yours to choose." },
    { q: "Should I take a supplement if my diet is not perfect?",
      a: "This article goes through the supplements that are marketed for ageing and what has actually been tested. A specific deficiency found on a blood test is a different matter, and that is a consultation rather than a purchase." },
    { q: "Does sleep matter as much as exercise?",
      a: "Sleep affects nearly everything this article covers, and it is one of the few things with no cost attached. It is worth fixing before anything is bought." },
    { q: "Which tests at AJSMC are worth doing at 40?",
      a: "The article lists what makes sense and what does not. Those are ordinary tests, run in the laboratory in the building, Monday to Saturday, 10am to 9pm. Call 044 2532 2021 to ask which of them need a fast." },
  ],
  "pre-marital-check-up": [
    { q: "Is pre-marital screening compulsory anywhere in India?",
      a: "No. The National Health Mission's 2016 haemoglobinopathies guideline says carrier screening before marriage is \"to be offered to those individuals or couples who seek it\", and binds itself to the WHO position that genetic testing should always be voluntary. Section 5 of the HIV and AIDS (Prevention and Control) Act, 2017 requires informed consent for any HIV test, and section 6's list of exceptions does not include marriage. No enacted, notified and enforced state law making any pre-marital test compulsory could be traced to a primary source." },
    { q: "If I am found to be a thalassaemia carrier, will I become unwell?",
      a: "No. Beta-thalassaemia trait means one altered copy of the gene, which causes no illness and needs no treatment. It can be associated with a mildly low MCV and MCH, which is why iron deficiency is sometimes mistaken for it and why the guideline asks for serum ferritin in borderline results. Carrier status matters for whom you have children with, not for your own health." },
    { q: "We are not related to each other. Do we still need carrier screening?",
      a: "Carrier screening is not about being related. Beta-thalassaemia, HbE and HbS trait occur across unrelated Indian populations, at rates that varied from 0 to 9.3% across 59 ethnic groups in the ICMR six-city study. Being related raises the chance that two people carry the same recessive variant; it is not what creates the possibility." },
    { q: "Can a laboratory or doctor give my HIV result to my family or my fiance?",
      a: "No. Section 8(1) of the HIV and AIDS (Prevention and Control) Act, 2017 forbids compelling anyone to disclose their HIV status except by order of a court, and forbids a person in a fiduciary relationship from disclosing another's status except with informed consent recorded in writing. Section 9 permits a physician or counsellor to inform a partner only where four strict conditions are met, and forbids it where the woman may face violence or abandonment." },
    { q: "I was screened for thalassaemia at college. Do we need to repeat it before the wedding?",
      a: "If you hold the actual report and it names the method, usually not for you; carrier status does not change. What still has to happen is that your partner is tested, since a single result is uninterpretable on its own. Bring the old report with its date and the method used, because a primary screening test such as NESTROFT is not the same as confirmation by complete blood count and HPLC." },
  ],
  "semen-analysis-explained": [
    { q: "My semen report says everything is normal. Does that rule out a male factor?",
      a: "No. The AUA/ASRM guideline states that values falling above or below the lower limit do not by themselves predict either fertility or infertility, and that semen parameters vary substantially from test to test. A normal-looking report narrows the possibilities but does not close the question, which is why AUA/ASRM assesses both partners at the same time rather than stopping when one set of results looks acceptable." },
    { q: "My report uses a word like oligoasthenozoospermia. What does that actually mean?",
      a: "It is a descriptive label meaning the sample had both a low sperm concentration and reduced motility on the day it was examined. WHO's sixth edition (2021) dropped these terms as a classification system, though many Indian laboratories still print them. Read it as a description of one sample, not a diagnosis and not a name for the man. What matters is which measurements were low, by how much, and what a repeat sample shows." },
    { q: "Should my partner be tested at the same time, or should I wait for my results first?",
      a: "At the same time. AUA/ASRM statement 1 advises initiating concurrent assessment of both partners, and NICE NG257 recommends further clinical assessment and investigation of both partners after a year without conception. Running them in sequence adds months and can leave a treatable factor in one partner undetected while the other is being investigated. The Urological Society of India notes that in India the male partner is bypassed in the majority of infertile couples." },
    { q: "An ultrasound reported a varicocele but the doctor could not feel one. Does it need treating?",
      a: "No. AUA/ASRM statement 27 is a Strong Recommendation against varicocelectomy for varicoceles detected solely by imaging, citing a systematic review of 7 trials in 548 participants that found no demonstrable benefit. The EAU says the same about subclinical varicocele and about any man whose semen analysis is normal. A varicocele that is new, large, cannot be reduced when lying down or is isolated on the right is a separate matter and needs abdominal imaging." },
    { q: "Is it worth taking supplements while waiting for the next test?",
      a: "The evidence does not support it. AUA/ASRM statement 45 says the benefits of supplements and antioxidants are of questionable clinical utility and that existing data are inadequate to recommend any specific agent. The 2022 Cochrane review covered 90 randomised trials and 10,303 subfertile men across around twenty agents and could recommend none; when trials at high risk of bias were excluded, the apparent benefit disappeared. NICE NG257 recommendation 1.24.6 advises against them outright for sperm DNA integrity." },
  ],
  "female-infertility-tests": [
    { q: "Does my husband need to be tested at the same time, or can I start on my own?",
      a: "You can start on your own, but half the evaluation is his and a semen analysis is part of it from the beginning. Doing yours first and his months later is the second commonest way time is lost on this." },
    { q: "Which day of my cycle should I book the first appointment on?",
      a: "The first appointment is a conversation and can be on any day. The tests that follow are timed, some to the early follicular phase and one to the mid-luteal phase, which is why the article asks you to bring your recent period dates." },
    { q: "I have already had these tests at another hospital. Will they all be repeated?",
      a: "Not necessarily. Bring the reports with the dates they were done and, where you have it, the cycle day. A result with no date or cycle day attached usually cannot be interpreted and is the kind that gets repeated." },
    { q: "Can I come for this on my own, and does it stay private?",
      a: "Yes. You can book for yourself and consultations are private. If there is anything you would rather raise without your partner in the room, say so when you arrive." },
    { q: "Which department at AJSMC do I book, and what should I bring?",
      a: "Outpatient consultations run Monday to Saturday, 10am to 9pm, at Police Commissioner Office Road, Egmore, on 044 2532 2021. Bring your recent period dates, previous scans and hormone reports with their dates, and your partner's semen analysis if one has been done. AJSMC does not perform ART." },
  ],
  "sti-testing-window-period": [
    { q: "I tested negative four weeks after the exposure. Is that final?",
      a: "It depends entirely on which test was run. Four weeks sits inside the window period for several assays: CDC gives 18 to 90 days for a rapid antigen/antibody finger-stick test and 23 to 90 days for antibody tests, which covers most rapid kits and self-tests, and NACO's antibody figure runs on average to three months. For syphilis, BASHH's 2024 UK guideline says a negative result within three months of infection cannot exclude early syphilis. Take the report to the doctor so the interval can be judged against the assay actually used, and expect that a repeat may be advised." },
    { q: "Is an HIV self-test bought online a result I can rely on?",
      a: "Not as a final answer. HIV self-testing is not offered under India's national programme, and NACO's position is that a self-test is a screening test only, not a confirmatory test of HIV status. Most self-tests are antibody tests, which carry the longest window of all. A reactive self-test needs confirmation at an Integrated Counselling and Testing Centre, where the national algorithm uses three assays based on different serological principles." },
    { q: "Can an employer or a hospital require an HIV test before giving me a job or treating me?",
      a: "Section 3 of the HIV and AIDS (Prevention and Control) Act, 2017 lists, among prohibited acts of discrimination against a protected person, requiring an HIV test as a pre-requisite for obtaining employment, or for accessing healthcare services, education or any other service or facility, or for their continuation. Separately, section 5 of the same Act provides that no HIV test may be performed on any person except with informed consent, and that the consent must include pre-test and post-test counselling." },
    { q: "Should I stop having sex while waiting for results?",
      a: "Yes, and the Indian guidelines put a clear end point on it. NACO advises abstaining from intercourse until treatment is complete and symptoms have resolved, and for genital ulcer disease until treatment is completed or the lesions have healed, whichever comes later. The reasoning is not only about the person waiting: it also prevents a treated partner being reinfected by an untreated one." },
    { q: "My partner has been diagnosed but my test came back negative. What happens now?",
      a: "Do not treat that negative as the end of it. The Indian guidelines use a 60-day look-back for urethral discharge, painful scrotal swelling and pelvic inflammatory disease, meaning partners whose last contact fell within 60 days before symptoms or diagnosis should be evaluated and treated, and CDC applies the same 60 days for chlamydia and gonorrhoea. Your own test may also have been taken inside its window. Say at the consultation which infection your partner was diagnosed with and when the last contact was, because both change what is advised." },
  ],
};
